#########
#
# workshop-template-b, evanwill
# a Jekyll template for a simple workshop website
# https://github.com/evanwill/workshop-template-b
#
#########

#######
# SITE SETTINGS
#
# title appears in the header
# title: "Beyond Vision: Multimodal Perspectives for Cross-View Geo-Localization"
title: WACV 2026 Tutorial
# title-icon appears in the header to give some pizazz (leave blank for none)
# choose from Bootstrap Icons in _includes/bootstrap-icons
# find names on https://icons.getbootstrap.com/
# some options: code-slash file-code gear tools lightblub book bookmark-star
title-icon: compass
# description, keywords, and image for meta tags
# these do not visibility appear on the pages, but used for SEO
description: "WACV 2026 tutorial, Beyond Vision: Multimodal Perspectives for Cross-View Geo-Localization"
keywords: "Computer Vision, WACV, visual geo-localization, cross-view geo-localization, Large Vision-Language Models"
# featured-image is added to metadata tags for social media sharing
# use a relative path to image in this repository or full URL
featured-image: "/images/uidaho-workshop.jpg"
# add search box to footer? true/false
search: false

# author settings for cc-by, appears in the footer and credits
author: Xiaohan Zhang
# your github username for link [optional]
github_username: zxh009123
# year or date published
pub_year: 2026
# location of code, the full url to your github repository
source-code: https://github.com/zxh009123/WACV26_CVGL_Tutorial

##########
# URL VARIABLES [optional!!]
#
# Optional if using GitHub Pages! If building manually, these must be set correctly.
# When using github pages just leave these blank!
#
# use url for the domain, e.g. https://evanwill.github.io
# on gh-pages follow the pattern: https://username.github.io
url:
# use baseurl to add subsection of the domain, e.g. /workshop-template-b
# on gh-pages this is a / followed by the name of the repository
# baseurl is your github repository's name prefixed with a /
baseurl:


##########
# ROBOTS EXCLUDE [optional!]
#
# set noindex to true if you do NOT want Google to index your site
# noindex: true 


#######
# BUILD SETTINGS [usually leave as is]
#
# Defaults to simplify front matter
defaults:
  - scope:
      path: "content"
    values:
      layout: "section"
# ignore stuff
exclude: [README.md, LICENSE, assets/lib/README.md]
# Build settings
markdown: kramdown
